### ISSUE TITLE
cookies are not being set in browser

### ISSUE THREAD

**Issue by quangas** [flolu/ssr-auth#1]
Any ideas on why the cookies themselves are not set?

After the github auth, calling setTokens, the cookie is not shown in the browser > cookies.

**Comment by flolu** [comment]
Hm interesting. Which browser do you use? Maybe your browser hides certain cookies?

Are there any errors in the terminal logs?

Do you stay signed in after refreshing the page?

**Comment by flolu** [comment]
I will close this issue due to inactivity for now. Feel free to reopen if necessary.
